name: Yolo5 Microservice Deployment

on:
  push:
    paths:
      - 'yolo5/**'
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Checkout the repo code
        uses: actions/checkout@v2

      - name: Build and push image
        run: |
          cd yolo5
          # Login to DockerHub (comment out if you don't use DockerHub):
          docker login -u ${{ secrets.DOCKERHUB_USERNAME}} -p ${{ secrets.DOCKERHUB_PASSWORD }}

          YOLO5_IMAGE_NAME=polybot:${{ github.run_number }}
          docker build -t $YOLO5_IMAGE_NAME .
          docker tag $YOLO5_IMAGE_NAME ${{ secrets.DOCKERHUB_USERNAME}}/$YOLO5_IMAGE_NAME
          docker push ${{ secrets.DOCKERHUB_USERNAME}}/$YOLO5_IMAGE_NAME

  Deploy:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Update Launch Template and Refresh ASG
        run: |
          # Run the Docker container
          aws ec2 create-launch-template-version --launch-template-id ${{ secrets.LAUNCH_TEMPLATE_ID }} --source-version ${{ secrets.LAUNCH_TEMPLATE_VERSION }} --launch-template-data '{"UserData":" #!/bin/bash docker pull ${{ secrets.DOCKERHUB_USERNAME }}/yolo5:latest docker stop yolo5 || true sudo docker rm yolo5 || true docker run -d --name yolo5 --restart always -p 8081:8081 ${{ secrets.DOCKERHUB_USERNAME }}/yolo5:latest"}'
          
          # Get the new version number
          NEW_VERSION=$(aws ec2 describe-launch-template-versions --launch-template-id ${{ secrets.LAUNCH_TEMPLATE_ID }} --query "LaunchTemplateVersions[-1].VersionNumber" --output text)
          
          # Set the new version as the default
          aws ec2 modify-launch-template --launch-template-id ${{ secrets.LAUNCH_TEMPLATE_ID }} --default-version $NEW_VERSION
          
          # Start an instance refresh for the Auto Scaling Group
          aws autoscaling start-instance-refresh --auto-scaling-group-name ${{ secrets.ASG_NAME }}
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}